condense_wildcard_suffixes = true
edition = "2021"
fn_call_width = 100
fn_single_line = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
struct_lit_single_line = false
struct_lit_width = 50
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true